# Generated by Django 3.2.7 on 2021-10-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_booking_user_book_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['created_at']},
        ),
    ]
